[build.environment]
  NODE_VERSION = "14"

[build]
  publish = "docs/dist"
  command = "find ./docs -type f -path \"*.md\" | xargs sed -i \"s/https:\/\/raw.githubusercontent.com\/saqqdy\/browsers/https:\/\/gitee.com\/saqqdy\/browsers\/raw/g\" && sed -i \"s/base: '\/browsers\/'/base: '\/'/g\" docs/.vitepress/config.ts && pnpm run docs:build && git checkout . && git clean -fd"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
